// Code generated by protoc-gen-go.
// source: event.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	event.proto
	files.proto

It has these top-level messages:
	Report
	Notification
	FileSetRequest
	FileSetResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Report struct {
	Serial       string            `protobuf:"bytes,1,opt,name=serial" json:"serial,omitempty"`
	HardwareAddr string            `protobuf:"bytes,2,opt,name=hardware_addr" json:"hardware_addr,omitempty"`
	Location     string            `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Version      map[string]uint64 `protobuf:"bytes,4,rep,name=version" json:"version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *Report) Reset()                    { *m = Report{} }
func (m *Report) String() string            { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()               {}
func (*Report) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Report) GetVersion() map[string]uint64 {
	if m != nil {
		return m.Version
	}
	return nil
}

type Notification struct {
	Group   string `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	Version uint64 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *Notification) Reset()                    { *m = Notification{} }
func (m *Notification) String() string            { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()               {}
func (*Notification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Report)(nil), "rpc.Report")
	proto.RegisterType((*Notification)(nil), "rpc.Notification")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Events service

type EventsClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Events_StreamClient, error)
}

type eventsClient struct {
	cc *grpc.ClientConn
}

func NewEventsClient(cc *grpc.ClientConn) EventsClient {
	return &eventsClient{cc}
}

func (c *eventsClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Events_StreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Events_serviceDesc.Streams[0], c.cc, "/rpc.Events/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventsStreamClient{stream}
	return x, nil
}

type Events_StreamClient interface {
	Send(*Report) error
	Recv() (*Notification, error)
	grpc.ClientStream
}

type eventsStreamClient struct {
	grpc.ClientStream
}

func (x *eventsStreamClient) Send(m *Report) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eventsStreamClient) Recv() (*Notification, error) {
	m := new(Notification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Events service

type EventsServer interface {
	Stream(Events_StreamServer) error
}

func RegisterEventsServer(s *grpc.Server, srv EventsServer) {
	s.RegisterService(&_Events_serviceDesc, srv)
}

func _Events_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventsServer).Stream(&eventsStreamServer{stream})
}

type Events_StreamServer interface {
	Send(*Notification) error
	Recv() (*Report, error)
	grpc.ServerStream
}

type eventsStreamServer struct {
	grpc.ServerStream
}

func (x *eventsStreamServer) Send(m *Notification) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eventsStreamServer) Recv() (*Report, error) {
	m := new(Report)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Events_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Events",
	HandlerType: (*EventsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Events_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x14, 0xc4, 0xc9, 0x66, 0x8d, 0xfa, 0xe2, 0xfa, 0x27, 0x20, 0x84, 0x3d, 0x2d, 0x7b, 0xaa, 0x20,
	0x41, 0x56, 0x10, 0xf1, 0xbe, 0x57, 0x0f, 0x0a, 0x5e, 0x25, 0xb6, 0x4f, 0x0d, 0xd6, 0x26, 0xbc,
	0xa6, 0x95, 0x7e, 0x17, 0x3f, 0xac, 0x6d, 0x5a, 0xb0, 0xc7, 0x99, 0xcc, 0xcc, 0x2f, 0x09, 0x48,
	0x6c, 0xb1, 0x8a, 0x26, 0x90, 0x8f, 0x5e, 0x71, 0x0a, 0xf9, 0xf6, 0x97, 0x81, 0x78, 0xc2, 0xe0,
	0x29, 0xaa, 0x53, 0x10, 0x35, 0x92, 0xb3, 0xa5, 0x66, 0x1b, 0x96, 0x1d, 0xab, 0x4b, 0x58, 0x7d,
	0x5a, 0x2a, 0x7e, 0x2c, 0xe1, 0xab, 0x2d, 0x0a, 0xd2, 0x8b, 0x64, 0x9f, 0xc3, 0x51, 0xe9, 0x73,
	0x1b, 0x9d, 0xaf, 0x34, 0x4f, 0xce, 0x15, 0x1c, 0xb6, 0x48, 0xf5, 0x60, 0x2c, 0x37, 0x3c, 0x93,
	0x3b, 0x6d, 0xfa, 0x69, 0x33, 0xce, 0x9a, 0x97, 0xf1, 0x68, 0x5f, 0x45, 0xea, 0xd6, 0x06, 0x4e,
	0xe6, 0x5a, 0x49, 0xe0, 0x5f, 0xd8, 0x4d, 0xc0, 0x15, 0x1c, 0xb4, 0xb6, 0x6c, 0x30, 0x81, 0x96,
	0x0f, 0x8b, 0x7b, 0xb6, 0xed, 0xf3, 0x8f, 0x3e, 0xba, 0x77, 0x37, 0x02, 0x87, 0xc8, 0x07, 0xf9,
	0x26, 0x4c, 0x8d, 0xb3, 0x7f, 0x72, 0xea, 0xec, 0xee, 0x40, 0xec, 0x87, 0x27, 0xd6, 0xea, 0x1a,
	0xc4, 0x73, 0x24, 0xb4, 0xdf, 0x4a, 0xce, 0x6e, 0xb3, 0xbe, 0x48, 0x62, 0xbe, 0x99, 0xb1, 0x1b,
	0xf6, 0x26, 0xd2, 0x97, 0xdc, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xe8, 0xa3, 0xae, 0x21,
	0x01, 0x00, 0x00,
}
