// Code generated by protoc-gen-go.
// source: event.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	event.proto
	files.proto

It has these top-level messages:
	Report
	Notification
	FileSetRequest
	FileSetResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Report struct {
	HardwareAddr string            `protobuf:"bytes,2,opt,name=hardware_addr" json:"hardware_addr,omitempty"`
	Location     string            `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Version      map[string]uint64 `protobuf:"bytes,4,rep,name=version" json:"version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *Report) Reset()                    { *m = Report{} }
func (m *Report) String() string            { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()               {}
func (*Report) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Report) GetHardwareAddr() string {
	if m != nil {
		return m.HardwareAddr
	}
	return ""
}

func (m *Report) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Report) GetVersion() map[string]uint64 {
	if m != nil {
		return m.Version
	}
	return nil
}

type Notification struct {
	Group   string `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	Version uint64 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *Notification) Reset()                    { *m = Notification{} }
func (m *Notification) String() string            { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()               {}
func (*Notification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Notification) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Notification) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*Report)(nil), "rpc.Report")
	proto.RegisterType((*Notification)(nil), "rpc.Notification")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Events service

type EventsClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Events_StreamClient, error)
}

type eventsClient struct {
	cc *grpc.ClientConn
}

func NewEventsClient(cc *grpc.ClientConn) EventsClient {
	return &eventsClient{cc}
}

func (c *eventsClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Events_StreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Events_serviceDesc.Streams[0], c.cc, "/rpc.Events/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventsStreamClient{stream}
	return x, nil
}

type Events_StreamClient interface {
	Send(*Report) error
	Recv() (*Notification, error)
	grpc.ClientStream
}

type eventsStreamClient struct {
	grpc.ClientStream
}

func (x *eventsStreamClient) Send(m *Report) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eventsStreamClient) Recv() (*Notification, error) {
	m := new(Notification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Events service

type EventsServer interface {
	Stream(Events_StreamServer) error
}

func RegisterEventsServer(s *grpc.Server, srv EventsServer) {
	s.RegisterService(&_Events_serviceDesc, srv)
}

func _Events_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventsServer).Stream(&eventsStreamServer{stream})
}

type Events_StreamServer interface {
	Send(*Notification) error
	Recv() (*Report, error)
	grpc.ServerStream
}

type eventsStreamServer struct {
	grpc.ServerStream
}

func (x *eventsStreamServer) Send(m *Notification) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eventsStreamServer) Recv() (*Report, error) {
	m := new(Report)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Events_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Events",
	HandlerType: (*EventsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Events_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "event.proto",
}

func init() { proto.RegisterFile("event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xc9, 0x66, 0x8d, 0x3a, 0xd9, 0x45, 0x0d, 0x08, 0xa1, 0xa7, 0xd2, 0x53, 0x05, 0x09,
	0x52, 0x41, 0xc4, 0x7b, 0xaf, 0x1e, 0x14, 0xbc, 0x4a, 0x6c, 0x47, 0x2d, 0xd6, 0x26, 0x4c, 0xd3,
	0x4a, 0xff, 0x83, 0x3f, 0x5a, 0x9a, 0x0a, 0xdb, 0xe3, 0x7b, 0xc9, 0x7b, 0xdf, 0xcc, 0x80, 0xc4,
	0x11, 0xbb, 0x60, 0x3c, 0xb9, 0xe0, 0x14, 0x27, 0x5f, 0x65, 0xbf, 0x0c, 0xc4, 0x13, 0x7a, 0x47,
	0x41, 0x5d, 0xc2, 0xfe, 0xd3, 0x52, 0xfd, 0x63, 0x09, 0x5f, 0x6d, 0x5d, 0x93, 0xde, 0xa4, 0x2c,
	0x3f, 0x55, 0xe7, 0x70, 0xd2, 0xba, 0xca, 0x86, 0xc6, 0x75, 0x9a, 0x47, 0xe7, 0x0a, 0x8e, 0x47,
	0xa4, 0x7e, 0x36, 0xb6, 0x29, 0xcf, 0x65, 0xa1, 0x0d, 0xf9, 0xca, 0x2c, 0x35, 0xe6, 0x65, 0x79,
	0x2a, 0xbb, 0x40, 0x53, 0x62, 0x60, 0xb7, 0xd6, 0x4a, 0x02, 0xff, 0xc2, 0x49, 0xb3, 0xd8, 0xb3,
	0x87, 0xa3, 0xd1, 0xb6, 0x03, 0x46, 0xd0, 0xf6, 0x61, 0x73, 0xcf, 0x32, 0x03, 0xbb, 0x47, 0x17,
	0x9a, 0xf7, 0x66, 0x01, 0xce, 0x5f, 0x3e, 0xc8, 0x0d, 0xfe, 0x3f, 0x71, 0x76, 0x20, 0xc7, 0x4c,
	0x71, 0x07, 0xa2, 0x9c, 0x57, 0xea, 0xd5, 0x35, 0x88, 0xe7, 0x40, 0x68, 0xbf, 0x95, 0x5c, 0x4d,
	0x93, 0x5c, 0x44, 0xb1, 0xee, 0xcc, 0xd9, 0x0d, 0x7b, 0x13, 0xf1, 0x04, 0xb7, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xda, 0xeb, 0xb0, 0x68, 0x11, 0x01, 0x00, 0x00,
}
