// Code generated by protoc-gen-go.
// source: files.proto
// DO NOT EDIT!

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FileSetRequest struct {
	Groups []string `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
}

func (m *FileSetRequest) Reset()                    { *m = FileSetRequest{} }
func (m *FileSetRequest) String() string            { return proto.CompactTextString(m) }
func (*FileSetRequest) ProtoMessage()               {}
func (*FileSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *FileSetRequest) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

type FileSetResponse struct {
	Sets map[string]*FileSetResponse_VersionedSet `protobuf:"bytes,1,rep,name=sets" json:"sets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *FileSetResponse) Reset()                    { *m = FileSetResponse{} }
func (m *FileSetResponse) String() string            { return proto.CompactTextString(m) }
func (*FileSetResponse) ProtoMessage()               {}
func (*FileSetResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *FileSetResponse) GetSets() map[string]*FileSetResponse_VersionedSet {
	if m != nil {
		return m.Sets
	}
	return nil
}

type FileSetResponse_VersionedSet struct {
	Version uint64            `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Set     map[uint64]string `protobuf:"bytes,2,rep,name=set" json:"set,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *FileSetResponse_VersionedSet) Reset()                    { *m = FileSetResponse_VersionedSet{} }
func (m *FileSetResponse_VersionedSet) String() string            { return proto.CompactTextString(m) }
func (*FileSetResponse_VersionedSet) ProtoMessage()               {}
func (*FileSetResponse_VersionedSet) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

func (m *FileSetResponse_VersionedSet) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FileSetResponse_VersionedSet) GetSet() map[uint64]string {
	if m != nil {
		return m.Set
	}
	return nil
}

func init() {
	proto.RegisterType((*FileSetRequest)(nil), "rpc.FileSetRequest")
	proto.RegisterType((*FileSetResponse)(nil), "rpc.FileSetResponse")
	proto.RegisterType((*FileSetResponse_VersionedSet)(nil), "rpc.FileSetResponse.VersionedSet")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FileSet service

type FileSetClient interface {
	Get(ctx context.Context, in *FileSetRequest, opts ...grpc.CallOption) (*FileSetResponse, error)
}

type fileSetClient struct {
	cc *grpc.ClientConn
}

func NewFileSetClient(cc *grpc.ClientConn) FileSetClient {
	return &fileSetClient{cc}
}

func (c *fileSetClient) Get(ctx context.Context, in *FileSetRequest, opts ...grpc.CallOption) (*FileSetResponse, error) {
	out := new(FileSetResponse)
	err := grpc.Invoke(ctx, "/rpc.FileSet/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileSet service

type FileSetServer interface {
	Get(context.Context, *FileSetRequest) (*FileSetResponse, error)
}

func RegisterFileSetServer(s *grpc.Server, srv FileSetServer) {
	s.RegisterService(&_FileSet_serviceDesc, srv)
}

func _FileSet_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSetServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.FileSet/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSetServer).Get(ctx, req.(*FileSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileSet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.FileSet",
	HandlerType: (*FileSetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _FileSet_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "files.proto",
}

func init() { proto.RegisterFile("files.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0xd1, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x80, 0x61, 0x36, 0x5b, 0x5b, 0x33, 0xd1, 0x16, 0x46, 0x0f, 0x21, 0x07, 0x89, 0x3d, 0x85,
	0x22, 0x4b, 0x89, 0x07, 0x45, 0xcf, 0xea, 0xcd, 0x83, 0x01, 0xef, 0x5a, 0x47, 0x09, 0x86, 0xec,
	0xba, 0x33, 0x29, 0xf4, 0xee, 0x33, 0xf8, 0xbc, 0xd2, 0xa4, 0x96, 0x28, 0x05, 0x6f, 0xbb, 0xf0,
	0xef, 0xc7, 0xb0, 0x03, 0xd1, 0x6b, 0x59, 0x11, 0x1b, 0xe7, 0xad, 0x58, 0xd4, 0xde, 0x2d, 0xa6,
	0x29, 0x8c, 0x6f, 0xcb, 0x8a, 0x0a, 0x92, 0x07, 0xfa, 0x68, 0x88, 0x05, 0xc7, 0x30, 0x7c, 0xf3,
	0xb6, 0x71, 0x1c, 0xab, 0x54, 0x67, 0xe1, 0xf4, 0x2b, 0x80, 0xc9, 0x36, 0x61, 0x67, 0x6b, 0x26,
	0x3c, 0x83, 0x01, 0x93, 0x74, 0x45, 0x94, 0x9f, 0x18, 0xef, 0x16, 0xe6, 0x4f, 0x63, 0x0a, 0x12,
	0xbe, 0xa9, 0xc5, 0xaf, 0x92, 0x4f, 0x05, 0x07, 0x8f, 0xe4, 0xb9, 0xb4, 0x35, 0xbd, 0x14, 0x24,
	0x38, 0x81, 0xd1, 0xb2, 0xbb, 0xc7, 0x2a, 0x55, 0xd9, 0x00, 0x2f, 0x40, 0x33, 0x49, 0x1c, 0xb4,
	0xdc, 0x6c, 0x27, 0xd7, 0x07, 0xd6, 0x76, 0x47, 0xcf, 0x60, 0xff, 0xe7, 0x8c, 0x11, 0xe8, 0x77,
	0x5a, 0x6d, 0xc4, 0x43, 0xd8, 0x5b, 0x3e, 0x55, 0x0d, 0xc5, 0x41, 0xaa, 0xb2, 0xf0, 0x2a, 0xb8,
	0x54, 0xc9, 0x3d, 0x84, 0xdb, 0x99, 0xfa, 0x71, 0x88, 0xf3, 0x7e, 0x1c, 0xe5, 0xa7, 0xff, 0x0e,
	0xb0, 0xf6, 0xf2, 0x6b, 0x18, 0x6d, 0x1a, 0x9c, 0x83, 0xbe, 0x23, 0xc1, 0xa3, 0xdf, 0x0f, 0xdb,
	0xff, 0x4c, 0x8e, 0x77, 0x69, 0xcf, 0xc3, 0x76, 0x07, 0xe7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x07, 0x9a, 0xe6, 0x45, 0x92, 0x01, 0x00, 0x00,
}
